# Generated by Django 5.0.13 on 2025-03-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-published_date']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
