# Generated by Django 5.0.13 on 2025-03-27 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
    ]
