# Generated by Django 5.0.13 on 2025-04-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_profile_linkedin_remove_profile_twitter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
